+incdir+../rtl
+incdir+../rtl/library
+incdir+../dut_rm
+incdir+../tb/include
+incdir+../tb/interface
+incdir+../tb/packages
+incdir+../tb/env
+incdir+../tb/env/agent
+incdir+../tb/env/agent/driver
+incdir+../tb/env/agent/monitor
+incdir+../tb/env/agent/sequencer
+incdir+../tb/env/scoreboard
+incdir+../tb/subscriber
+incdir+../tb/sequences
+incdir+../tb/sequences/and_sequences
+incdir+../tb/sequences/logical_sequences
+incdir+../tb/sequences/shift_sequences
+incdir+../tb/sequences/arithmetic_sequences
+incdir+../tb/sequences/bitmanip_sequences
+incdir+../tb/sequences/csr_sequences
+incdir+../tb/sequences/negative_sequences
+incdir+../tb/sequences/random_sequences
+incdir+../tb/tests

../rtl/rtl_pkg.sv
../rtl/rtl_lib_wrapper.sv
../rtl/Bit_Manipulation_Unit.sv

../tb/include/uvm_def.sv
../tb/interface/Bit_Manipulation_intf.sv
../tb/packages/dut_test_package.sv
../tb/top_tb.sv
